<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="src/CSS/reset.css">
        <link rel="stylesheet" href="src/CSS/login.css">
        <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
        <title>Document</title>
    </head>
    <body>
        <header>
            <img src='../../img/handshake.png' alt="Logo">
        </header>
        <main>
            
            <label for="name">Usuario</label>
            <input type="text" id="name" placeholder="Digite seu usuario">

            <label for="senha">Senha</label>
            <input type="text" id="senha" placeholder="Digite sua senha">
            
            <div>
                <a href="/src/HTML/cadastro.html">Entrar</a>
            </div>
            
        </main>
        
        
    </body>
</html>

theme: jekyll-theme-cayman